### PR TITLE
Allow numeric values when creating certain elements from the HTML factory

### PR DESCRIPTION
**Pull request by Vusys**
This allows numeric values (i.e. they pass `is_numeric`) when creating a label or span from the factory methods in the Html class.

I bumped into an issue where labels would throw an `InvalidChild` exception with integer labels. E.g.

```php
html()->label(5); //throws InvalidChild
```

As a work around, you can cast the value to a string first or use the `text()` or `html()` method. So for example, these are equivalent to the above except they do not throw an exception. 

```php
html()->label((string)5);

html()->label()->html(5);

html()->label()->text(5);
```

This PR fixes the underlying issue by expanding the check against invalid children by also allowing numeric values.

I've added tests for integers and floats, as well as integers in hexadecimal and octal form.

I was planning of adding tests to ensure the exception is thrown for other invalid data, however it is currently possible to write something like:

```php
html()->label(['foo', 'bar']);
```

I would expect this to throw an exception, however in actuality you end up with:

```html
<label>foobar</label>
```

I could address this, but it would break BC.

### CODE REVIEW

**Comment by Vusys** [comment]
HAL, please open the ~~pod bay doors~~ pull request.

**Comment by freekmurze** [comment]
I’m afraid I can’t do that Dave 🤪

**Comment by Vusys** [comment]
@freekmurze is there a problem with the PR? It's mostly a bug fix.

**Comment by freekmurze** [comment]
> I’m afraid I can’t do that Dave 🤪

O, I forgot to open it again, sorry about that, will review it soon!

**Comment by sebastiandedeyne** [comment]
Thanks!

**Pull request merged**
