### PR TITLE
Add autocomplete attribute helper to input, select and textarea

### PR DESCRIPTION
**Pull request by raveren**
```blade
{{ html()->text('my_column')->placeholder(trans('my_column_placeholder'))->autocomplete('off') }}
```

### CODE REVIEW

**Comment by freekmurze** [comment]
Very nice, thanks!

**Comment by raveren** [comment]
appreciated 🥰

**Comment by raveren** [comment]
Oh I remember this one, I tried it out (putting autocomplete attribute on the form) and it didn't work as expected in the browser so I must have just skipped it. Hm, my bad sorry, it should be included.

I'll try to do a PR when I can :)

**Comment by hyungseob** [comment]
I'm curious about one more thing 
For button(), the 'id' is not automatically created. Is it really like that?

**Comment by raveren** [comment]
this is totally the wrong place to ask that and I'm not even a maintainer, but yeah `id` is predictably not generated automatically for button elements
image

**Comment by raveren** [comment]
this is totally the wrong place to ask that and I'm not even a maintainer, but yeah id is predictably not generated automatically for button elements
image

**Pull request merged**
